name: Code validation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP validator
        run: find . -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

      - name: PHPCSFixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.1.0
        with:
          args: --config=.php-cs-fixer.dist.php --diff --dry-run
